---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aoc2020
  region: ap-southeast-1
  version: '1.18'

# :: pods in the following namespaces will launch under the Fargate configuration
fargateProfiles:
  - name: aoc2020fp
    selectors:
      - namespace: benchmarking
      - namespace: kube-system

iam:
  withOIDC: true
  # serviceAccounts:
  #   - metadata:
  #       name: benchmark-process
  #       namespace: benchmarking
  #     attachPolicy:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Allow
  #           Resource: '*'
  #           Action:
  #             - logs:CreateLogStream
  #             - logs:CreateLogGroup
  #             - logs:DescribeLogStreams
  #             - logs:PutLogEvents

cloudWatch:
  clusterLogging:
    enableTypes: ['*']
