---
apiVersion: batch/v1
kind: Job

metadata:
  name: benchmarking

spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: benchmarkprocess
          image: '214400071163.dkr.ecr.ap-southeast-1.amazonaws.com/aoc2020:latest'
          args: ['001', 'easy']
